name: "Main"
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install cspell
        run: |
          cd ${{github.workspace}}
          npm install -g cspell
      - name: Check spelling
        run: cspell **/*.md
